apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: ingress-nm
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 2021pietcshemant077@poornima.org
    profile: tlsserver
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
